FROM python:3.10-slim

WORKDIR /app
 
COPY frontend/requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
 
COPY frontend/app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
